openapi: 3.1.0
info:
  title: iGSP Reference API
  version: 1.0.0
  description: |
    iGaming Standard Protocol — Reference API for providers.
servers:
  - url: https://api.igsp.dev/v1
paths:
  /games:
    get:
      summary: Games
      responses:
        '200':
          description: List of games
  /sessions:
    post:
      summary: Create a new gaming session
      responses:
        '201':
          description: Session created
  /providers:
    get:
      summary: Providers
      responses:
        '200':
          description: List of providers
